name: Update Jira on Pull Request

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Send update to Jira
        env:
          JIRA_BASE_URL: "https://yourcompany.atlassian.net"
          JIRA_API_TOKEN: ${{ secrets.ATATT3xFfGF00zzyXmvKIE9ul4kdza6t0XmqtdRXt-bFY9sz1ckhBhk1txkLJY9Xpz-TRJumfJpb0mAUkYNR9Ek2ZWcseP272x15BA0GV6ZGlXuSE-kKgaDjCj_u3G_e0KjH-VSlE04jtYvnRF4H2v_RL6-A30Z21s4J97G3q5vXkUR4AKCaSME=2B39E396 }}
          JIRA_USER_EMAIL: "deha@sabanciuniv.edu"
        run: |
          curl -X POST -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"transition": {"id": "31"}}' \
          "$https://cs308-22.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiMTcxMzg5OGM4ZjFlNGEzOGIxZGM4NGJkN2Y3ZmJiM2EiLCJwIjoiaiJ9/rest/api/3/issue/CS308/transitions"
